print("Welcome to the Band Name Generator!")
print("Please enter the name of the city you grew up in:")
city = input()
print("Please enter the name of your pet:")
pet = input()
print("Your band name could be " + city + " " + pet + ".")